version: '3.2'

services:
    database:
      image: mongo
      restart: always
      volumes:
        - database path here
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 00000